# Generated by Django 5.0.6 on 2024-06-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
