# Generated by Django 5.0.6 on 2024-07-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_remove_testcaseexpectedoutput_test_case_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarytestcase',
            name='problem',
        ),
    ]
