# Generated by Django 5.0.6 on 2024-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_alter_problem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=50),
        ),
    ]
