# Generated by Django 5.0.7 on 2024-07-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_alter_problem_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
    ]
