# Generated by Django 5.0.6 on 2024-07-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
