# Generated by Django 5.0.6 on 2024-07-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
