# Generated by Django 5.0.6 on 2024-06-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_delete_submission'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.language'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
