# Generated by Django 5.0.6 on 2024-07-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
