# Generated by Django 5.0.6 on 2024-07-02 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='expected_output',
        ),
        migrations.CreateModel(
            name='ExpectedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField()),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_outputs', to='submissions.testcase')),
            ],
        ),
    ]
