# Generated by Django 5.0.6 on 2024-07-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_temporaryproblem_title_problemtestcase_and_more'),
        ('submissions', '0005_remove_testcase_expected_output_expectedoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedoutput',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_expected_outputs', to='submissions.testcase'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submmision_test_cases', to='problems.problem'),
        ),
    ]
